name: isolate_executor
description: A simple command-line application.
version: 1.0.0
homepage: https://github.com/0htls/isolate_executor

environment:
  sdk: '>=2.15.0 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.19.5
